<?php
$produtoSetor = $_SESSION['setorProduto'] ?? [];

?>
<div class="table-responsive shadow-sm border rounded-3">
    <table class="table table-hover align-middle m-0">
        <thead class="table-danger" style="font-size: 0.8rem; white-space: nowrap;">
            <tr>
                <th class="ps-4" style="width: 40px;">
                    <input class="form-check-input" type="checkbox" id="checkAll">
                </th>
                <th>Cód Produto</th>
                <th>Produto</th> 
                <th>Cód Setor</th> 
                <th>Setor</th> 
                <th>Qtd Atual</th> 
                <th>Qtd Máx</th>
                <th>Qtd Mín</th>
                <th>Custo Médio</th>
                <th>Preço Custo</th>
                <th>Preço Venda</th>
                <th class="pe-4">Referência</th>
            </tr>
        </thead>
        <tbody class="text-secondary" style="font-size: 0.95rem;">
            <?php foreach ($produtoSetor as $value) : ?>
                <tr>
                    <td class="ps-4">
                        <input class="form-check-input row-checkbox" type="checkbox" name="item[]" value="">
                    </td>
                    <td class="fw-bold text-dark">#<?=$value['PRODUTO_ID']?></td>
                    <td class="fw-medium text-dark text-capitalize text-truncate" style="max-width: 250px;">
                        <?=$value['PRD_NOME']?>
                    </td>
                    <td class="fw-bold text-dark">#<?=$value['SETOR_ID']?></td>
                    <td class="fw-medium text-dark text-capitalize text-truncate" style="max-width: 250px;">
                        <?=$value['STR_NOME']?>
                    </td>
                    <td class="fw-medium text-dark text-capitalize text-truncate" style="max-width: 250px;">
                        <?=$value['SP_QUANTIDADE_ATUAL']?>
                    </td>
                    <td class="fw-medium text-dark text-capitalize text-truncate" style="max-width: 250px;">
                        <?=$value['SP_QUANTIDADE_MAXIMA']?>
                    </td>
                    <td class="fw-medium text-dark text-capitalize text-truncate" style="max-width: 250px;">
                        <?=$value['SP_QUANTIDADE_MINIMA']?>
                    </td>
                    <td class="fw-medium text-dark text-capitalize text-truncate" style="max-width: 250px;">
                        <?=$value['SP_PRODUTO_CUSTO_MEDIO']?>
                    </td>
                    <td class="fw-medium text-dark text-capitalize text-truncate" style="max-width: 250px;">
                        <?=$value['SP_PRECO_CUSTO']?>
                    </td>
                    <td class="fw-medium text-dark text-capitalize text-truncate" style="max-width: 250px;">
                       <?=$value['SP_PRECO_VENDA']?>
                    </td>
                    <td>
                        <?=$value['SP_PRODUTO_LOCAL_INTERNO']?>
                    </td>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>
</div>