<div class="table-responsive shadow-sm border rounded-3">
    <table class="table table-hover align-middle m-0">
        <thead class="table-danger" style="font-size: 0.8rem; white-space: nowrap;">
            <tr>
                <th class="ps-4" style="width: 40px;">
                    <input class="form-check-input" type="checkbox" id="checkAll">
                </th>
                <th>Código</th>
                <th>Descrição</th> 
                <th>Ncm</th> 
                <th>Data Registro</th> 
                <th>Status</th>
                <th>Categoria</th>
                <th class="pe-4">Finalidade</th>
            </tr>
        </thead>
        <tbody class="text-secondary" style="font-size: 0.95rem;">
            <tr>
                <td class="ps-4">
                    <input class="form-check-input row-checkbox" type="checkbox" name="item[]" value="">
                </td>
                <td class="fw-bold text-dark">#1</td>
                <td class="fw-medium text-dark text-capitalize text-truncate" style="max-width: 250px;">
                    teste
                </td>
                <td class="fw-medium text-dark text-capitalize text-truncate" style="max-width: 250px;">
                    teste2
                </td>
                <td class="fw-medium text-dark text-capitalize text-truncate" style="max-width: 250px;">
                    teste3
                </td>
                <td>
                    <span class="badge border bg-success-subtle text-success border-success-subtle fw-normal">teste4</span>
                </td>
                <td><span class="fw-medium text-dark">teste5</span></td>
                <td class="fw-medium text-dark pe-4">teste6</td>
            </tr>
        </tbody>
    </table>
</div>