<div class="table-responsive shadow-sm border rounded-3">
    <table class="table table-hover align-middle m-0">
        <thead class="table-danger" style="font-size: 0.8rem; white-space: nowrap;">
            <tr>
                <th class="ps-4" style="width: 40px;">
                    <input class="form-check-input" type="checkbox" id="checkAll">
                </th>
                <th>Cód Produto</th>
                <th>Produto</th> 
                <th>Cód Setor</th> 
                <th>Setor</th> 
                <th>Qtd Atual</th> 
                <th>Qtd Máx</th>
                <th>Qtd Mín</th>
                <th>Custo Médio</th>
                <th>Preço Custo</th>
                <th>Preço Venda</th>
                <th class="pe-4">Referência</th>
            </tr>
        </thead>
        <tbody class="text-secondary" style="font-size: 0.95rem;">
            <tr>
                <td class="ps-4">
                    <input class="form-check-input row-checkbox" type="checkbox" name="item[]" value="">
                </td>
                <td class="fw-bold text-dark">#1</td>
                <td class="fw-medium text-dark text-capitalize text-truncate" style="max-width: 250px;">
                    carro
                </td>
                <td class="fw-bold text-dark">#1</td>
                <td class="fw-medium text-dark text-capitalize text-truncate" style="max-width: 250px;">
                    Venda
                </td>
                <td class="fw-medium text-dark text-capitalize text-truncate" style="max-width: 250px;">
                    3
                </td>
                <td class="fw-medium text-dark text-capitalize text-truncate" style="max-width: 250px;">
                    5
                </td>
                <td class="fw-medium text-dark text-capitalize text-truncate" style="max-width: 250px;">
                    2
                </td>
                <td class="fw-medium text-dark text-capitalize text-truncate" style="max-width: 250px;">
                    8,90
                </td>
                <td class="fw-medium text-dark text-capitalize text-truncate" style="max-width: 250px;">
                    6,90
                </td>
                <td class="fw-medium text-dark text-capitalize text-truncate" style="max-width: 250px;">
                    12,90
                </td>
                <td>
                    <button>Ver</button>
                </td>
            </tr>
        </tbody>
    </table>
</div>