<div class="container mt-5">
  <div class="row">
    <div id="imagem-central" class="col-12 d-flex justify-content-center flex-column align-items-center">
      <img src="/assets/img/imagemcentral.jpg" alt="estoquePRO" class="img-fluid">
      <div class="text-center mt-3">
        <p class="fw-bold fs-5 mb-0">
          ESTOQUE<span class="text-danger">PRO</span>
        </p>
        <p class="fst-italic"><b>Gestão inteligente para o seu estoque.<b></p>
        </div>
      </div>  
    </div>
  </div>