<?php 
$acao = $this->view->form['acao'];
$prodMod = $this->view->form['dados']['formProdutoAcao'];
if (isset($_SESSION['produto']) && !empty($_SESSION['produto']) && count($_SESSION['produto']) >= 3){
    components('produto','modal');
}
?>
<div class="container mt-5 mb-5">
    <div class="card shadow-sm">
        <div class="card-header bg-white">
            <h5 class="mb-0"><?= $this->view->form['acao'] ?? ''?> de Produto</h5>
        </div>
        <div class="card-body">
            <form method="post" action="<?= $this->view->form['action'] ?? '' ?>">
                <div class="<?= ($acao == 'Visualização' || $acao == 'Exclusão') ? 'pe-none' : ''  ?>">
                    <div class="row mb-3">
                        <div class="col-md-8">
                            <label class="form-label">Nome do Produto</label>
                            <input type="text" class="form-control " placeholder="Nome produto" name="produto"
                            value="<?=$this->view->form['dados']['formProdutoAcao']['PRD_NOME'] ?? '' ?>">
                        </div>

                        <div class="col-md-4">
                            <label class="form-label">NCM</label>
                            <input type="text" class="form-control" placeholder="0000.00.00" name="ncm"
                            value="<?=$this->view->form['dados']['formProdutoAcao']['PRD_NCM'] ?? '' ?>">
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-4">
                            <label class="form-label">Categoria</label>
                            <select class="form-select" name="categoria">
                                <?php foreach($this->view->form['dados']['categoria'] as $value):?>
                                    <option value="<?=$value['CATEGORIA_ID']?>"
                                        <?= (isset($prodMod['PRD_CATEGORIA_ID']) && 
                                         $prodMod['PRD_CATEGORIA_ID'] == $value['CATEGORIA_ID']) ? 'selected' : ''?>
                                    ><?=$value['CAT_NOME']?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label class="form-label">Grupo Finalidade</label>
                            <select class="form-select" name="grupo">
                                <?php foreach($this->view->form['dados']['finalidade'] as $value):?>
                                    <option value="<?=$value['GRUPO_PRD_FIN_ID']?>"
                                         <?= (isset($prodMod['PRD_GRUPO_FIN_ID']) && 
                                         $prodMod['PRD_GRUPO_FIN_ID'] == $value['GRUPO_PRD_FIN_ID']) ? 'selected' : ''?>
                                    ><?=$value['GRP_NOME']?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label class="form-label">Setor</label>
                            <select class="form-select" name="setor">
                                <?php foreach($this->view->form['dados']['setor'] as $value):?>
                                    <option value="<?=$value['SETOR_ID']?>"><?=$value['STR_NOME']?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                        
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-3">
                           <label class="form-label">Preço Custo</label>
                                    <input type="number" class="form-control" placeholder="00.00" name="precoCusto"
                                    value="<?=$prodMod['SP_PRECO_CUSTO'] ?? '' ?>">
                        </div>
                        <div class="col-md-3">
                            <label class="form-label">Preço Venda</label>
                                    <input type="number" class="form-control" placeholder="00.00" name="precoVenda"
                                    value="<?=$prodMod['SP_PRECO_VENDA'] ?? '' ?>">
                        </div>
                        <div class="col-md-3">
                            <label class="form-label">Custo Médio</label>
                                    <input type="number" class="form-control" placeholder="00.00" name="custoMedio" disabled
                                    value="<?=$prodMod['SP_PRODUTO_CUSTO_MEDIO'] ?? '' ?>">
                        </div>

                        <div class="col-md-3">
                            <label class="form-label">Status</label>
                            <select class="form-select" name="status">
                                <option value="1"
                                   <?= (isset($prodMod['PRD_STATUS_ID']) && $prodMod['PRD_STATUS_ID'] == 1) ? 'selected' : ''?> 
                                >Ativo</option>
                                <option value="2"
                                    <?= (isset($prodMod['PRD_STATUS_ID']) && $prodMod['PRD_STATUS_ID'] == 2) ? 'selected' : ''?>
                                >Inativo</option>
                            </select>
                        </div>
                        
                    </div>

                </div>

                <div class="text-end">
                    <a href="/produto/listagem" class="btn btn-light me-2">Voltar</a>
                    <?php if (isset($this->view->form['acao']) && $this->view->form['acao']  != 'Visualização') :?>
                        <button type="submit" class="btn btn-primary px-5">Salvar Produto</button>
                    <?php endif; ?>
                </div>
            </form>
        </div>
    </div>
</div>