<div class="container d-flex justify-content-center align-items-center mt-5">
    <div class="row w-75 rounded shadow-sm mb-5">

        <!-- LADO ESQUERDO -->
        <div class="col-md-5 bg-light p-2 p-md-4 d-flex flex-column justify-content-center">
            <img src="/assets/img/icon-fundo.png" class="img-fluid mb-3 m-auto" width="120" alt="ESTOQUEPRO">

            <p class="fw-bold fs-4 mb-1 text-center">
                ESTOQUE<span class="text-danger">PRO</span>
            </p>

            <p class="text-muted mb-3 text-center">
                Gestão inteligente para o seu estoque.
            </p>

            <ul class="list-unstyled m-auto">
                <li><i class="bi bi-check2-square text-success"></i> Controle de produtos</li>
                <li><i class="bi bi-check2-square text-success"></i> Gestão eficiente</li>
                <li><i class="bi bi-check2-square text-success"></i> Relatórios claros</li>
            </ul>
        </div>

        <!-- LADO DIREITO -->
        <div class="col-md-7 p-2 p-md-4">
            <form action="/login/autenticar" method="post">
                <div class="mb-3">
                    <label class="form-label">Login</label>
                    <input type="text" class="form-control" placeholder="Digite seu usuário" name="usuario">
                </div>

                <div class="mb-3">
                    <label class="form-label">Senha</label>
                    <input type="password" class="form-control" placeholder="Digite sua senha" name="senha">
                </div>

                <div class="mb-1">
                    <i class="bi bi-person-lock"></i>
                    <a href="/recuperarSenha">Recuperar senha</a>
                </div>

                <span class="text-danger"><?= session('error') ?></span>
                <div class="text-center mt-3">
                    <button type="submit" class="btn btn-outline-danger w-100">Entrar</button>
                </div>
            </form>
        </div>

    </div>
</div>
