<div class="container-fluid">
    <div class="row bg-white p-2 d-flex align-items-center mb-3">
        <div class="col-md-8 d-flex text-start">
            <form class="d-flex flex-row">
                <input type="radio" class="btn-check btn-dan" name="options-outlined" id="success-outlined" autocomplete="off" value="produto">
                <label class="btn btn-outline-primary ajuste-tamanho me-2" for="success-outlined">Produto</label>


                <input type="radio" class="btn-check" name="options-outlined" id="danger-outlined" autocomplete="off" value="setor">
                <label class="btn btn-outline-danger ajuste-tamanho me-2" for="danger-outlined">Setor</label>
                <select class="form-select ajuste-tamanho me-2 d-none" id="selectSetor" name="setor">
                    <option value="1">Venda</option>
                    <option value="2">Revenda</option>
                </select>
                <button type="submit" class="btn btn-outline-dark ajuste-tamanho">
                    <i class="bi bi-funnel-fill "></i>
                </button>
            </form>
        </div>



        <div class="col-md-4 text-end">
            <div>
                <a href="/produto/cadastro" class="btn btn-outline-danger btn-sm px-3">
                    <i class="bi bi-plus-lg"></i> Cadastrar
                </a>

                <button class="btn btn-outline-primary btn-sm px-3" id="btnProdutoVisualizar" type="submit">
                    <i class="bi bi-eye-fill"></i> Visualizar
                </button>

                <button class="btn btn-outline-warning btn-sm px-3" id="btnProdutoEditar">
                    <i class="bi bi-pencil"></i> Editar
                </button>

                <button class="btn btn-outline-secondary btn-sm px-3" id="btnProdutoExcluir">
                    <i class="bi bi-trash"></i> Excluir
                </button>
            </div>
        </div>
    </div>

    
        <?php
        if (isset($_GET['options-outlined']) && $_GET['options-outlined'] == 'setor') {
            components('estoque','tabelaSetor');
        } else if (isset($_GET['options-outlined']) && $_GET['options-outlined'] == 'produto'){
            components('estoque','tabelaProduto');
        }else{
        ?>
            <div class="container mt-5">
                <div class="row">
                    <div id="imagem-central" class="col-12 d-flex justify-content-center flex-column align-items-center">
                        <img src="/assets/img/imagemcentral.jpg" alt="estoquePRO" class="img-fluid">
                        <div class="text-center mt-3">
                            <p class="fw-bold fs-5 mb-0">ESTOQUE<span class="text-danger">PRO</span></p>
                            <p class="fst-italic"><b>Gestão inteligente para o seu estoque.<b></p>
                        </div>
                    </div>  
                </div>
            </div>
        <?php } ?>
   
    </div>
</div>