<?php 
$acao = $this->view->form['acao'];
$setores = $this->view->setor['dados']['setor'];
$produtos = $this->view->setor['dados']['produto'] ?? [];
$prodMod = $this->view->setor['dados']['formEstoqueAcao'];
if (isset($_SESSION['setorProduto']) && !empty($_SESSION['setorProduto']) && count($_SESSION['setorProduto']) >= 3){
   components('estoque','modal');
}
?>
<div class="container mt-5 mb-5">
    <div class="card shadow-sm">
        <div class="card-header bg-white d-flex">
            <div class=""> 
                <h5 class="mb-0"><?= $this->view->form['acao'] ?? ''?> de Produto em Setor</h5>
            </div>
            <div class="ms-auto text-end">
                <input type="text" 
                disabled
                class="form-control text-center p-0" 
                style="width: 30px; height: 30px; line-height: 30px; display: inline-block;"
                value="<?=($prodMod) ? $prodMod['SETOR_ESTOQUE_ID'] : ''?>">
            </div>
        </div>
        <div class="card-body">
            <form method="post" action="<?= $this->view->form['action'] ?? '' ?>">
                <div class="<?= ($acao == 'Visualização' || $acao == 'Exclusão') ? 'pe-none' : ''  ?>">
                    <div class="row mb-3">
                        <div class="col-md-8">
                            <label class="form-label">Produto</label>
                            <select class="form-select" name="produto">

                                <?php foreach($produtos as $value):?>
                                    <option value="<?=$value['PRODUTO_ID']?>"
                                        <?= (isset($prodMod['SP_PRODUTO_ID']) && 
                                        $prodMod['SP_PRODUTO_ID'] == $value['PRODUTO_ID']) ? 'selected' : ''?>
                                        ><?=$value['PRD_NOME']?></option>
                                    <?php endforeach;?>

                                </select>
                            </div>

                            <div class="col-md-4">
                                <label class="form-label">Setor</label>
                                <select class="form-select" name="setor">

                                    <?php foreach($setores as $value):?>
                                        <option value="<?=$value['SETOR_ID']?>"
                                            <?= (isset($prodMod['SP_SETOR_ID']) && 
                                            $prodMod['SP_SETOR_ID'] == $value['SETOR_ID']) ? 'selected' : ''?>
                                            ><?=$value['STR_NOME']?></option>
                                        <?php endforeach;?>

                                    </select>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <div class="col-md-4">
                                    <label class="form-label">Quantidade Atual</label>
                                    <input type="number" class="form-control" placeholder="0.0000" name="qtdAtual"
                                    value="<?=$prodMod['SP_QUANTIDADE_ATUAL'] ?? '' ?>">
                                </div>

                                <div class="col-md-4">
                                    <label class="form-label">Quantidade Máxima</label>
                                    <input type="number" class="form-control" placeholder="0.0000" name="qtdMax"
                                    value="<?=$prodMod['SP_QUANTIDADE_MAXIMA'] ?? '' ?>">
                                </div>

                                <div class="col-md-4">
                                    <label class="form-label">Quantidade Mínima</label>
                                    <input type="number" class="form-control" placeholder="0.0000" name="qtdMin"
                                    value="<?=$prodMod['SP_QUANTIDADE_MINIMA'] ?? '' ?>">
                                </div>

                                <div class="col-md-4">
                                    <label class="form-label">Preço Custo</label>
                                    <input type="number" class="form-control" placeholder="00.00" name="precoCusto"
                                    value="<?=$prodMod['SP_PRECO_CUSTO'] ?? '' ?>">
                                </div>

                                <div class="col-md-4">
                                    <label class="form-label">Preço Venda</label>
                                    <input type="number" class="form-control" placeholder="00.00" name="precoVenda"
                                    value="<?=$prodMod['SP_PRECO_VENDA'] ?? '' ?>">
                                </div>

                                <div class="col-md-4">
                                    <label class="form-label">Custo Médio</label>
                                    <input type="number" class="form-control" placeholder="00.00" name="custoMedio" disabled
                                    value="<?=$prodMod['SP_PRODUTO_CUSTO_MEDIO'] ?? '' ?>">
                                </div>

                                <div class="mt-3 col-md-12" >
                                  <label for="referencia" class="form-label">Referência</label>
                                  <textarea class="form-control" id="referencia" rows="2" name="ref" placeholder="Digite a localização do produto"><?=$prodMod['SP_PRODUTO_LOCAL_INTERNO'] ?? ''?></textarea>
                              </div>
                          </div>

                      </div>
                      <div class="text-end">
                        <a href="/estoque" 
                        class="btn btn-light me-2">Voltar</a>
                        <?php if (isset($this->view->form['acao']) && $this->view->form['acao']  != 'Visualização') :?>
                            <button type="submit" class="btn btn-primary px-5">Salvar Produto</button>
                        <?php endif; ?>
                    </div>
                </form>
            </div>
        </div>
    </div>